### ISSUE TITLE
Rename 'Terms & Resources' and 'Terms' titles

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#133]
'Terms' feels a little too school-like, and so I wanted to change these titles:

![screen shot 2015-01-30 at 14 12 03](https://cloud.githubusercontent.com/assets/7372432/5976842/2b706db0-a88a-11e4-9586-3ce124242aea.png)

...but noticed that there's some hard-coding:

![screen shot 2015-01-29 at 20 11 04](https://cloud.githubusercontent.com/assets/7372432/5976858/51560b8e-a88a-11e4-86a3-1ea0f3952113.png)

...and that there are translations of this text:

![screen shot 2015-01-29 at 20 12 41](https://cloud.githubusercontent.com/assets/7372432/5976865/643ecf42-a88a-11e4-86df-ee42641811aa.png)

Maybe 'Terms & Resources' could be '[language] Projects', and 'terms' could just be 'projects'?

**Comment by andylolz** [comment]
Currently a collection of projects is called a Term (the plural of which is of course “Terms”). Happy for a collection of projects to be called something else, but I don’t think the plural of that thing should be “Projects” because that would be confusing. You’d click through from a page of “Projects” (formerly “Terms”) to a page of “Projects”.

How would you want this to work ideally, @CodeClubRik? Here’s a suggestion:

 * Choose a language (English, Swedish, Norwegian…)
 * Choose a topic / medium (Scratch, HTML & CSS, Python)
 * Choose a level (Beginner, Intermediate, Advanced)
 * List of Projects

So I’ve added an extra step in there (level). For URLs, I’d suggest removing both levels and project numbers from URLs completely, and just leaving language and topic.

**Comment by CodeClubRik** [comment]
Hey @andylolz -- I agree, although I can't think of a suitable name for the 'topic/medium' bit. 'Language' (as in programming language) felt like a good fit, but we can't have `Language --> Language --> ...` :)

I'm not sure about the 'level' being Beginner, Intermediate or Advanced, as the difficulty really depends on how many challenges a child undertakes. Do 'Scratch 1' and 'Scratch 2' etc. work as 'levels'?

**Comment by andylolz** [comment]
To be honest, although we’re talking about a very minor change (in terms of code) I think this actually represents a fairly significant change in terms of branding. Elsewhere, the Code Club site talks about terms (e.g. the [about page](https://www.codeclub.org.uk/about)). This grouping of projects is a pretty crucial building block, so the language used to describe it should be consistent.

I’d suggest closing this ticket (since it’s not specific to projects pages, really) and having a chat with the wonderful @laurakirsop.
