### ISSUE TITLE
Adding new terms

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#136]
Currently I'm putting any project not in the 'core' curriculum into the 'Additional ... projects' sections, and these sections are getting quite big.

![screen shot 2015-02-03 at 13 21 15](https://cloud.githubusercontent.com/assets/7372432/6020768/c5b25b3e-aba7-11e4-956b-8d54f869323b.png)

It would be great if we had the flexibility to create new sections, which effectively worked in the same way that the 'Terms' section does (i.e. building projects from manifests, etc.)

This means that I could create a second 'additional terms' section, to distinguish it from the core curriculum (or maybe even a section per language). We could also create a 'third-party resources' section, for stuff like the TWSU projects, which are currently static here: [https://www.codeclub.org.uk/twsu](https://www.codeclub.org.uk/twsu).

**Comment by andylolz** [comment]
@CodeClubRik: Apologies – I’m not sure I understand. It sounds like you’re after more terms. Like this?

![screen shot 2015-02-03 at 13 47 18](https://cloud.githubusercontent.com/assets/464193/6021125/3d55819a-abab-11e4-806e-e8fa042a05ae.png)

If so, that’s currently possible. If not, can you explain how it differs?

> https://www.codeclub.org.uk/twsu

That URL doesn’t work for me…

**Comment by CodeClubRik** [comment]
Hey @andylolz -- I mean additional entire sections, so we could have an 'additional projects' section underneath the current 'terms' section. I know that @Jonic set a version of this up, but additional sections can only be URLs and not manifests which build projects.

**Comment by andylolz** [comment]
> I mean additional entire sections, so we could have an 'additional projects' section underneath the current 'terms' section

Like this?

![screen shot 2015-02-03 at 14 09 32](https://cloud.githubusercontent.com/assets/464193/6021526/58eb4144-abae-11e4-8e12-1c26bfd3cfb9.png)

Sorry – I find it much easier to understand with an image :) So… Here I’ve put the additional projects literally underneath, rather than underneath in terms of menu hierarchy.

**Comment by CodeClubRik** [comment]
Yep, that kind of thing! :)

**Comment by martinpeck** [comment]
This is now done:

- Each term .manifest file can [optionally] specify a category in the JSON
- That category is rendered as a H1 before rendering the link to the term
- That category is looked up in the language translations so that you can render a human-readable title if you want.
- [optionally] an additional translation, the category ID with ".description", can exist in the translations. If present, this will be rendered as a span below the category title.

So, if you have something like this in the .manifest...

```json
 {
    "description": false,
    "id": "scratch_01",
    "language": "en-GB",
    "number": 1,
    "title": "Scratch 1",
    "category": "cat-legacy",
```

... and you had something like this for the `cat-legacy` category in en-GB.languages...

```json
{
	"code": "en-GB",
	"name": "English",
	"registration_note": {},
	"legal": {},
	"translations": {
		"cat-official": "Terms",
		"cat-official.description" : "",
		"cat-legacy" : "Additional Projects",
		"cat-legacy.description" : "These are additional projects"
```

Then the title "Additional Projects" with the text "These are additional projects" will appear above this term, and every subsequent term rendered unless those subsequent terms change the category.

By default, all of this is optional and can be omitted, leaving the old behaviour intact.

**Comment by martinpeck** [comment]
Fixed in SHA: f505b4857636284aaf4cae11b3d2e93363ad902c
Minor modifications to metadata in SHA: 0c791857804c902c82b8325e1521a218ed973495

**Comment by martinpeck** [comment]
Sample output (with totally made up metadata) can be seen here:

![image](https://cloud.githubusercontent.com/assets/1524451/6803405/2e9e16a8-d22f-11e4-9583-c12078b369a3.png)

**Comment by andylolz** [comment]
Nice!

One thing about using translations in this way… The fallback (when there’s no translation) becomes a key (e.g. “cat-official.description”) rather than the English text. This is _only just_ worth mentioning, so I’m mentioning it :)

V nice though! I’ve commented on the commit directly with attempted answers to the questions in the comments.

**Comment by martinpeck** [comment]
Yeah...agreed. The use of translations is not ideal. My longer-term plan is to define the metadata for categories somewhere but this felt like the least-evil-while-getting-stuff-done way to give @CodeClubRik some more flexibility.

**Comment by andylolz** [comment]
Defos. Makes a lot of sense :+1:
