### ISSUE TITLE
Use a more memorable jumpto.cc URL at the start of every PDF (and page)

### ISSUE THREAD

**Issue by andylolz** [CodeClub/lesson_format#165]
Every PDF currently begins with:
![screen shot 2015-07-01 at 11 33 09](https://cloud.githubusercontent.com/assets/464193/8452684/11bf4dc8-1fe5-11e5-8ba9-eefc8a1dd6ff.png)

The jumpto.cc URL includes a case-sensitive alphanumeric string. A lowercase word or phrase would be more memorable/easier to type.

The UK version is set here:
https://github.com/CodeClub/lesson_format/blob/master/assets/themes/uk.theme#L5

The world version is set here:
https://github.com/CodeClub/lesson_format/blob/master/assets/themes/world.theme#L5

[As far as the user journey goes for someone with an existing, unregistered club, it’s all round the houses. That’s a separate issue.]

**Comment by CodeClubRik** [comment]
I can create a new short link - something like `/reg-help`, `/reg-blog` or `/why-reg`?
I'm terrible at thinking up short links.

**Comment by andylolz** [comment]
> I'm terrible at thinking up short links.

I think readable/understandable is better than short. `/why-register`? Or `/register`?

**Comment by martinpeck** [comment]
Either way, if we are to do this then it should be an additional short url, not an update to the existing one, cos we obviously can't update printed copies of PDFs.

Can we? No....no I'm sure we can't. Be cool if we could. But we can't. So...let's stop wondering about whether we can or not. We almost certainly can't.

(It's hot today - I'm losing it)

p.s. /start-a-club or /register-today (calls to action, rather than questions) would be my suggestion. They're a bit more "peppy" and would make me shout "Hell yes! I most certainly will! Just see if I don't!!!"

(again, the heat is getting to me)

**Comment by CodeClubRik** [comment]
> p.s. /start-a-club or /register-today (calls to action, rather than questions) would be my suggestion. 

Is this confusing, as we also have codeclub.org.uk/start-a-club. This is just a blog for more info.

**Comment by martinpeck** [comment]
What do we want people who click that link to do? We want them to start a club, right? We take them to a blog that explains **why** we want them to start a club, and give them links to codeclub.org.uk/start-a-club. 

The blog endpoint is a "sticking plaster" cos we don't have better words for why anyone would do this on the main site, so today that's where it goes. But that doesn't mean the short url should be any less clear as to what you're going to do when you click it.

Also, my suggestion is "won't fix" for this bug anyway, unless this is a pressing concern (i.e. we know people are trying to type the URL and failing) as this will all be done differently come the revolution.

What I would rather do is fix plinky so that it performs case-insensitive lookups.

FYI, since we launched plinky (just over a week) we've had 81 requests for the correct short url and 5 case-incorrect typos.

**Comment by martinpeck** [comment]
There - see what you made me do now...! 
martinpeck/plinky/issues/1

**Comment by andylolz** [comment]
Ah – This wasn’t intended to be a ticket about case sensitivity. It was about making the URL more memorable/easier to type. So rather than: “people are trying to type the URL and failing”, it’s: “people are not attempting to type the complicated URL”.

**Comment by andylolz** [comment]
> and give them links to codeclub.org.uk/start-a-club

This then takes them to:
https://www.codeclub.org.uk/start-a-club/volunteers
…and then to:
https://www.codeclub.org.uk/search-for-a-venue

If they have an existing, unregistered club, I suppose they’d then find the postcode for the school, enter that, then click through to the school. They then reach a page similar to this one:
https://www.codeclub.org.uk/register?role=Volunteer

I wonder if the blog could instead link to this? (Though I’m not sure where the journey goes after that.)

**Comment by martinpeck** [comment]
Closing this, as we no longer have this link at the top of the PDFs.
